spring:
  datasource:
    url: jdbc:h2:mem:testdb   # 또는 jdbc:h2:file:./data/botdb (파일 저장형)
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: shc.ywlee@gmail.com
    password: oamp klei mryb sueh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


secret-key: ThisStatementIsJwtSecretKeyDoNotUseThisStatement

##gmail 설정

