###아이디 중복 체크
POST http://localhost:8080/api/v1/auth/id-check
Content-Type: application/json

{
  "id": "test"
}

###이메일 인증번호 전송
POST http://localhost:8080/api/v1/auth/email-certification
Content-Type: application/json

{
  "id": "test",
  "email": "shc.ywlee@gmail.com"
}

###이메일 인증번호 체크
POST http://localhost:8080/api/v1/auth/check-certification
Content-Type: application/json

{
  "id": "test",
  "email": "shc.ywlee@gmail.com",
  "certificationNumber": "3911"
}

###회원가입
POST http://localhost:8080/api/v1/auth/sign-up
Content-Type: application/json

{
  "id": "test",
  "password": "sa02a1adfadf",
  "email": "shc.ywlee@gmail.com",
  "certificationNumber": "1123"
}